name: Release Extensions

on: [workflow_dispatch]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --ignore-scripts

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: node_modules/.cache/turbo
          key: turbo-${{ github.sha }}
          restore-keys: |
            turbo-

      - name: Build
        run: pnpm build

      - name: Upload Extension Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: extension-artifacts
          path: extension/dist

  Chrome:
    needs: Build
    name: Submit (Chrome)
    environment: Chrome
    runs-on: ubuntu-latest
    steps:
      - name: Download Extension Artifacts
        uses: actions/download-artifact@v4
        with:
          name: extension-artifacts
          path: artifacts
      - name: Submit to Chrome Web Store
        run: npx chrome-webstore-upload-cli@3 --source artifacts/chrome
        env:
          EXTENSION_ID: kmcfjchnmmaeeagadbhoofajiopoceel
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}

  Firefox:
    needs: Build
    name: Submit (Firefox)
    environment: Firefox
    runs-on: ubuntu-latest
    steps:
      - name: Download Extension Artifacts
        uses: actions/download-artifact@v4
        with:
          name: extension-artifacts
          path: artifacts
      - name: Submit to Firefox Add-ons
        run: npx web-ext@8 sign --channel listed -s artifacts/firefox
        env:
          WEB_EXT_API_KEY: ${{ secrets.FIREFOX_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.FIREFOX_API_SECRET }}
