name: Release Chrome Extension

on: [workflow_dispatch]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --ignore-scripts

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: node_modules/.cache/turbo
          key: turbo-${{ github.sha }}
          restore-keys: |
            turbo-

      - name: Build
        run: pnpm build
        env:
          CI: true

      - name: Submit Chrome Extension
        uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          file-path: packages/extension/dist/chrome.zip
          extension-id: kmcfjchnmmaeeagadbhoofajiopoceel
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}

      - name: Submit Firefox Extension
        run: cd packages/extension && pnpm dlx web-ext sign -s dist/firefox --api-key=${{ secrets.FIREFOX_API_KEY }} --api-secret=${{ secrets.FIREFOX_API_SECRET }}
